#!/bin/bash
#
# Fail2Ban Manager - Comprehensive brute-force protection
# Supports: SSH, Web (Apache/Nginx), Mail (Postfix/Dovecot), MySQL
#
# Usage: sudo ./fail2ban_script.sh
#
set -euo pipefail

JAIL_FILE="/etc/fail2ban/jail.local"
JAIL_DIR="/etc/fail2ban/jail.d"

check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "[-] Error: This script must be run as root."
        exit 1
    fi
}

detect_package_manager() {
    if command -v dnf &> /dev/null; then
        PM="dnf"; INSTALL="dnf install -y"; UPDATE="dnf makecache"
    elif command -v yum &> /dev/null; then
        PM="yum"; INSTALL="yum install -y"; UPDATE="yum makecache"
    elif command -v apt-get &> /dev/null; then
        PM="apt-get"; INSTALL="apt-get install -y"; UPDATE="apt-get update"
    elif command -v apk &> /dev/null; then
        PM="apk"; INSTALL="apk add"; UPDATE="apk update"
    elif command -v pacman &> /dev/null; then
        PM="pacman"; INSTALL="pacman -Sy --noconfirm"; UPDATE="pacman -Sy"
    else
        echo "[-] Unsupported package manager. Install manually."
        exit 1
    fi
}

detect_ssh_log() {
    # Auto-detect where SSH logs actually live to avoid Fail2Ban startup errors
    if [ -f "/var/log/auth.log" ]; then
        SSH_LOG="/var/log/auth.log"
    elif [ -f "/var/log/secure" ]; then
        SSH_LOG="/var/log/secure"
    else
        # Fallback to systemd backend if no files found
        SSH_LOG="systemd"
    fi
    echo "Detected SSH Log source: $SSH_LOG"
}

# Detect installed services
detect_services() {
    SERVICES=()

    # SSH
    if command -v sshd &>/dev/null || systemctl list-unit-files | grep -q sshd; then
        SERVICES+=("ssh")
    fi

    # Apache
    if command -v apache2 &>/dev/null || command -v httpd &>/dev/null; then
        SERVICES+=("apache")
    fi

    # Nginx
    if command -v nginx &>/dev/null; then
        SERVICES+=("nginx")
    fi

    # Postfix
    if command -v postfix &>/dev/null; then
        SERVICES+=("postfix")
    fi

    # Dovecot
    if command -v dovecot &>/dev/null; then
        SERVICES+=("dovecot")
    fi

    # MySQL/MariaDB
    if command -v mysql &>/dev/null || command -v mariadb &>/dev/null; then
        SERVICES+=("mysql")
    fi

    echo "Detected services: ${SERVICES[*]}"
}

# Configure Apache jail
configure_apache_jail() {
    echo "Configuring Apache jail..."

    # Detect Apache log paths
    local access_log error_log
    if [ -d "/var/log/apache2" ]; then
        access_log="/var/log/apache2/*access*.log"
        error_log="/var/log/apache2/*error*.log"
    elif [ -d "/var/log/httpd" ]; then
        access_log="/var/log/httpd/*access*.log"
        error_log="/var/log/httpd/*error*.log"
    else
        echo "Apache logs not found, skipping"
        return 1
    fi

    mkdir -p "$JAIL_DIR"
    cat > "${JAIL_DIR}/apache.conf" <<EOF
# Apache/httpd jails - Auto-generated by Security Toolkit

[apache-auth]
enabled  = true
port     = http,https
filter   = apache-auth
logpath  = ${error_log}
maxretry = 5
findtime = 600
bantime  = 3600

[apache-badbots]
enabled  = true
port     = http,https
filter   = apache-badbots
logpath  = ${access_log}
maxretry = 2
findtime = 600
bantime  = 86400

[apache-noscript]
enabled  = true
port     = http,https
filter   = apache-noscript
logpath  = ${error_log}
maxretry = 3
findtime = 600
bantime  = 3600

[apache-overflows]
enabled  = true
port     = http,https
filter   = apache-overflows
logpath  = ${error_log}
maxretry = 2
findtime = 600
bantime  = 3600

[apache-modsecurity]
enabled  = false
port     = http,https
filter   = apache-modsecurity
logpath  = ${error_log}
maxretry = 2
findtime = 600
bantime  = 3600
EOF
    echo "Apache jails configured"
}

# Configure Nginx jail
configure_nginx_jail() {
    echo "Configuring Nginx jail..."

    local access_log="/var/log/nginx/access.log"
    local error_log="/var/log/nginx/error.log"

    if [ ! -d "/var/log/nginx" ]; then
        echo "Nginx logs not found, skipping"
        return 1
    fi

    mkdir -p "$JAIL_DIR"
    cat > "${JAIL_DIR}/nginx.conf" <<EOF
# Nginx jails - Auto-generated by Security Toolkit

[nginx-http-auth]
enabled  = true
port     = http,https
filter   = nginx-http-auth
logpath  = ${error_log}
maxretry = 5
findtime = 600
bantime  = 3600

[nginx-limit-req]
enabled  = true
port     = http,https
filter   = nginx-limit-req
logpath  = ${error_log}
maxretry = 10
findtime = 600
bantime  = 3600

[nginx-botsearch]
enabled  = true
port     = http,https
filter   = nginx-botsearch
logpath  = ${access_log}
maxretry = 2
findtime = 600
bantime  = 86400
EOF
    echo "Nginx jails configured"
}

# Configure Postfix jail
configure_postfix_jail() {
    echo "Configuring Postfix jail..."

    local mail_log
    if [ -f "/var/log/mail.log" ]; then
        mail_log="/var/log/mail.log"
    elif [ -f "/var/log/maillog" ]; then
        mail_log="/var/log/maillog"
    else
        echo "Mail logs not found, skipping"
        return 1
    fi

    mkdir -p "$JAIL_DIR"
    cat > "${JAIL_DIR}/postfix.conf" <<EOF
# Postfix jails - Auto-generated by Security Toolkit

[postfix]
enabled  = true
port     = smtp,465,submission,587
filter   = postfix
logpath  = ${mail_log}
maxretry = 5
findtime = 600
bantime  = 3600

[postfix-sasl]
enabled  = true
port     = smtp,465,submission,587,imap,imaps
filter   = postfix[mode=auth]
logpath  = ${mail_log}
maxretry = 3
findtime = 600
bantime  = 7200

[postfix-rbl]
enabled  = false
port     = smtp,465,submission,587
filter   = postfix-rbl
logpath  = ${mail_log}
maxretry = 1
findtime = 600
bantime  = 86400
EOF
    echo "Postfix jails configured"
}

# Configure Dovecot jail
configure_dovecot_jail() {
    echo "Configuring Dovecot jail..."

    local mail_log
    if [ -f "/var/log/mail.log" ]; then
        mail_log="/var/log/mail.log"
    elif [ -f "/var/log/maillog" ]; then
        mail_log="/var/log/maillog"
    elif [ -f "/var/log/dovecot.log" ]; then
        mail_log="/var/log/dovecot.log"
    else
        echo "Dovecot logs not found, skipping"
        return 1
    fi

    mkdir -p "$JAIL_DIR"
    cat > "${JAIL_DIR}/dovecot.conf" <<EOF
# Dovecot jails - Auto-generated by Security Toolkit

[dovecot]
enabled  = true
port     = pop3,pop3s,imap,imaps,submission,sieve
filter   = dovecot
logpath  = ${mail_log}
maxretry = 5
findtime = 600
bantime  = 3600
EOF
    echo "Dovecot jails configured"
}

# Configure MySQL jail
configure_mysql_jail() {
    echo "Configuring MySQL/MariaDB jail..."

    local mysql_log
    if [ -f "/var/log/mysql/error.log" ]; then
        mysql_log="/var/log/mysql/error.log"
    elif [ -f "/var/log/mariadb/mariadb.log" ]; then
        mysql_log="/var/log/mariadb/mariadb.log"
    elif [ -f "/var/log/mysqld.log" ]; then
        mysql_log="/var/log/mysqld.log"
    else
        echo "MySQL logs not found - ensure error logging is enabled"
        return 1
    fi

    # Create custom filter for MySQL auth failures
    mkdir -p /etc/fail2ban/filter.d
    cat > /etc/fail2ban/filter.d/mysqld-auth.conf <<'EOF'
# MySQL/MariaDB authentication failure filter
[Definition]
failregex = ^.*Access denied for user.*from '<HOST>'.*$
            ^.*\[Warning\].*IP address '<HOST>' could not be resolved.*$
            ^.*Host '<HOST>' is blocked because of many connection errors.*$
ignoreregex =
EOF

    mkdir -p "$JAIL_DIR"
    cat > "${JAIL_DIR}/mysql.conf" <<EOF
# MySQL/MariaDB jails - Auto-generated by Security Toolkit

[mysqld-auth]
enabled  = true
port     = 3306
filter   = mysqld-auth
logpath  = ${mysql_log}
maxretry = 5
findtime = 600
bantime  = 3600
EOF
    echo "MySQL jails configured"
}

install_fail2ban() {
    echo "Updating package lists..."
    $UPDATE > /dev/null 2>&1

    echo "Installing Fail2Ban..."
    $INSTALL fail2ban > /dev/null 2>&1 || {
        echo "Install failed. Attempting EPEL (RHEL/CentOS)..."
        if [[ "$PM" == "dnf" || "$PM" == "yum" ]]; then
            $INSTALL epel-release > /dev/null 2>&1
            $UPDATE > /dev/null 2>&1
            $INSTALL fail2ban > /dev/null 2>&1
        fi
    }

    echo "Configuring SSH Jail..."
    detect_ssh_log

    # Backup existing config if present
    if [ -f "$JAIL_FILE" ]; then
        cp "$JAIL_FILE" "${JAIL_FILE}.bak.$(date +%s)"
        echo "Backed up existing config to ${JAIL_FILE}.bak.*"
    fi

    IGNORE_IP="127.0.0.1/8 ::1"

    # Write DEFAULT section with ignoreip so all jails inherit it
    cat <<EOF > $JAIL_FILE
[DEFAULT]
ignoreip = $IGNORE_IP

EOF

    # If using log files
    if [ "$SSH_LOG" != "systemd" ]; then
        cat <<EOF >> $JAIL_FILE
[sshd]
enabled = true
port    = ssh
filter  = sshd
logpath = $SSH_LOG
maxretry = 3
findtime = 600
bantime  = 86400
EOF
    else
        # If using systemd backend (modern/arch)
        cat <<EOF >> $JAIL_FILE
[sshd]
enabled = true
port    = ssh
filter  = sshd
backend = systemd
maxretry = 3
findtime = 600
bantime  = 86400
EOF
    fi

    echo "Restarting Fail2Ban..."
    if command -v systemctl &> /dev/null && [ -d /run/systemd/system ]; then
        systemctl enable fail2ban
        systemctl restart fail2ban
        if systemctl is-active --quiet fail2ban; then
            echo "Fail2Ban is ACTIVE and protecting SSH."
        else
            echo "Fail2Ban failed to start. Check 'systemctl status fail2ban'."
        fi
    elif command -v rc-service &> /dev/null; then
        # OpenRC (Alpine, Gentoo)
        rc-update add fail2ban default 2>/dev/null || true
        rc-service fail2ban restart
        if rc-service fail2ban status | grep -q "started"; then
            echo "Fail2Ban is ACTIVE and protecting SSH (OpenRC)."
        else
            echo "Fail2Ban may have failed to start. Check 'rc-service fail2ban status'."
        fi
    else
        service fail2ban restart
        echo "Fail2Ban restarted (sysvinit)."
    fi
}

# Install and configure fail2ban for ALL detected services
install_all_services() {
    echo "=== Installing Comprehensive Fail2Ban Protection ==="

    # First install fail2ban
    install_fail2ban

    # Detect available services
    detect_services

    echo ""
    echo "Configuring jails for detected services..."

    # Configure jails for each detected service
    for svc in "${SERVICES[@]}"; do
        case "$svc" in
            apache)
                configure_apache_jail || true
                ;;
            nginx)
                configure_nginx_jail || true
                ;;
            postfix)
                configure_postfix_jail || true
                ;;
            dovecot)
                configure_dovecot_jail || true
                ;;
            mysql)
                configure_mysql_jail || true
                ;;
        esac
    done

    # Restart fail2ban to load new jails
    echo ""
    echo "Reloading Fail2Ban with all jails..."
    if command -v systemctl &> /dev/null && [ -d /run/systemd/system ]; then
        systemctl restart fail2ban
    elif command -v rc-service &> /dev/null; then
        rc-service fail2ban restart
    else
        service fail2ban restart
    fi

    # Show status
    echo ""
    echo "=== Active Jails ==="
    fail2ban-client status 2>/dev/null || echo "Could not get status"
}

check_root
detect_package_manager

# Auto-install comprehensive protection (no menu)
install_all_services